# Generated by Django 3.2.16 on 2025-06-03 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20250603_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'default_related_name': '%(class)ss', 'verbose_name': 'избранное', 'verbose_name_plural': 'Избранные рецепты'},
        ),
    ]
