# Generated by Django 3.2.16 on 2025-05-14 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20250514_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Автор рецептов'),
        ),
    ]
